/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __DRD_DBUS_LIGHTDM_H__
#define __DRD_DBUS_LIGHTDM_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.deepin.DisplayManager.RemoteDisplayFactory.Session */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION (drd_dbus_lightdm_remote_display_factory_session_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION, DrdDBusLightdmRemoteDisplayFactorySession))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SESSION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION, DrdDBusLightdmRemoteDisplayFactorySessionIface))

struct _DrdDBusLightdmRemoteDisplayFactorySession;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySession DrdDBusLightdmRemoteDisplayFactorySession;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionIface DrdDBusLightdmRemoteDisplayFactorySessionIface;

struct _DrdDBusLightdmRemoteDisplayFactorySessionIface
{
  GTypeInterface parent_iface;

  const gchar * (*get_address) (DrdDBusLightdmRemoteDisplayFactorySession *object);

  const gchar * (*get_client_id) (DrdDBusLightdmRemoteDisplayFactorySession *object);

  const gchar * (*get_session_id) (DrdDBusLightdmRemoteDisplayFactorySession *object);

  const gchar * (*get_user_name) (DrdDBusLightdmRemoteDisplayFactorySession *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactorySession, g_object_unref)
#endif

GType drd_dbus_lightdm_remote_display_factory_session_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *drd_dbus_lightdm_remote_display_factory_session_interface_info (void);
guint drd_dbus_lightdm_remote_display_factory_session_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus property accessors: */
const gchar *drd_dbus_lightdm_remote_display_factory_session_get_user_name (DrdDBusLightdmRemoteDisplayFactorySession *object);
gchar *drd_dbus_lightdm_remote_display_factory_session_dup_user_name (DrdDBusLightdmRemoteDisplayFactorySession *object);
void drd_dbus_lightdm_remote_display_factory_session_set_user_name (DrdDBusLightdmRemoteDisplayFactorySession *object, const gchar *value);

const gchar *drd_dbus_lightdm_remote_display_factory_session_get_address (DrdDBusLightdmRemoteDisplayFactorySession *object);
gchar *drd_dbus_lightdm_remote_display_factory_session_dup_address (DrdDBusLightdmRemoteDisplayFactorySession *object);
void drd_dbus_lightdm_remote_display_factory_session_set_address (DrdDBusLightdmRemoteDisplayFactorySession *object, const gchar *value);

const gchar *drd_dbus_lightdm_remote_display_factory_session_get_session_id (DrdDBusLightdmRemoteDisplayFactorySession *object);
gchar *drd_dbus_lightdm_remote_display_factory_session_dup_session_id (DrdDBusLightdmRemoteDisplayFactorySession *object);
void drd_dbus_lightdm_remote_display_factory_session_set_session_id (DrdDBusLightdmRemoteDisplayFactorySession *object, const gchar *value);

const gchar *drd_dbus_lightdm_remote_display_factory_session_get_client_id (DrdDBusLightdmRemoteDisplayFactorySession *object);
gchar *drd_dbus_lightdm_remote_display_factory_session_dup_client_id (DrdDBusLightdmRemoteDisplayFactorySession *object);
void drd_dbus_lightdm_remote_display_factory_session_set_client_id (DrdDBusLightdmRemoteDisplayFactorySession *object, const gchar *value);


/* ---- */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY (drd_dbus_lightdm_remote_display_factory_session_proxy_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY, DrdDBusLightdmRemoteDisplayFactorySessionProxy))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY, DrdDBusLightdmRemoteDisplayFactorySessionProxyClass))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY, DrdDBusLightdmRemoteDisplayFactorySessionProxyClass))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_PROXY))

typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionProxy DrdDBusLightdmRemoteDisplayFactorySessionProxy;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionProxyClass DrdDBusLightdmRemoteDisplayFactorySessionProxyClass;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionProxyPrivate DrdDBusLightdmRemoteDisplayFactorySessionProxyPrivate;

struct _DrdDBusLightdmRemoteDisplayFactorySessionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  DrdDBusLightdmRemoteDisplayFactorySessionProxyPrivate *priv;
};

struct _DrdDBusLightdmRemoteDisplayFactorySessionProxyClass
{
  GDBusProxyClass parent_class;
};

GType drd_dbus_lightdm_remote_display_factory_session_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactorySessionProxy, g_object_unref)
#endif

void drd_dbus_lightdm_remote_display_factory_session_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DrdDBusLightdmRemoteDisplayFactorySession *drd_dbus_lightdm_remote_display_factory_session_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
DrdDBusLightdmRemoteDisplayFactorySession *drd_dbus_lightdm_remote_display_factory_session_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void drd_dbus_lightdm_remote_display_factory_session_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DrdDBusLightdmRemoteDisplayFactorySession *drd_dbus_lightdm_remote_display_factory_session_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
DrdDBusLightdmRemoteDisplayFactorySession *drd_dbus_lightdm_remote_display_factory_session_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON (drd_dbus_lightdm_remote_display_factory_session_skeleton_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON, DrdDBusLightdmRemoteDisplayFactorySessionSkeleton))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON, DrdDBusLightdmRemoteDisplayFactorySessionSkeletonClass))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON, DrdDBusLightdmRemoteDisplayFactorySessionSkeletonClass))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SESSION_SKELETON))

typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionSkeleton DrdDBusLightdmRemoteDisplayFactorySessionSkeleton;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionSkeletonClass DrdDBusLightdmRemoteDisplayFactorySessionSkeletonClass;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySessionSkeletonPrivate DrdDBusLightdmRemoteDisplayFactorySessionSkeletonPrivate;

struct _DrdDBusLightdmRemoteDisplayFactorySessionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  DrdDBusLightdmRemoteDisplayFactorySessionSkeletonPrivate *priv;
};

struct _DrdDBusLightdmRemoteDisplayFactorySessionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType drd_dbus_lightdm_remote_display_factory_session_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactorySessionSkeleton, g_object_unref)
#endif

DrdDBusLightdmRemoteDisplayFactorySession *drd_dbus_lightdm_remote_display_factory_session_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.deepin.DisplayManager.RemoteDisplayFactory */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY (drd_dbus_lightdm_remote_display_factory_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY, DrdDBusLightdmRemoteDisplayFactory))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY, DrdDBusLightdmRemoteDisplayFactoryIface))

struct _DrdDBusLightdmRemoteDisplayFactory;
typedef struct _DrdDBusLightdmRemoteDisplayFactory DrdDBusLightdmRemoteDisplayFactory;
typedef struct _DrdDBusLightdmRemoteDisplayFactoryIface DrdDBusLightdmRemoteDisplayFactoryIface;

struct _DrdDBusLightdmRemoteDisplayFactoryIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_create_remote_greeter_display) (
    DrdDBusLightdmRemoteDisplayFactory *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    const gchar *arg_address);

  gboolean (*handle_create_single_logon_session) (
    DrdDBusLightdmRemoteDisplayFactory *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    GVariant *arg_auth_fd,
    const gchar *arg_address);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactory, g_object_unref)
#endif

GType drd_dbus_lightdm_remote_display_factory_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *drd_dbus_lightdm_remote_display_factory_interface_info (void);
guint drd_dbus_lightdm_remote_display_factory_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void drd_dbus_lightdm_remote_display_factory_complete_create_remote_greeter_display (
    DrdDBusLightdmRemoteDisplayFactory *object,
    GDBusMethodInvocation *invocation,
    const gchar *session_path);

void drd_dbus_lightdm_remote_display_factory_complete_create_single_logon_session (
    DrdDBusLightdmRemoteDisplayFactory *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *session_path);



/* D-Bus method calls: */
void drd_dbus_lightdm_remote_display_factory_call_create_remote_greeter_display (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    const gchar *arg_address,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean drd_dbus_lightdm_remote_display_factory_call_create_remote_greeter_display_finish (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    gchar **out_session_path,
    GAsyncResult *res,
    GError **error);

gboolean drd_dbus_lightdm_remote_display_factory_call_create_remote_greeter_display_sync (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    const gchar *arg_address,
    gchar **out_session_path,
    GCancellable *cancellable,
    GError **error);

void drd_dbus_lightdm_remote_display_factory_call_create_single_logon_session (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    GVariant *arg_auth_fd,
    const gchar *arg_address,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean drd_dbus_lightdm_remote_display_factory_call_create_single_logon_session_finish (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    gchar **out_session_path,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean drd_dbus_lightdm_remote_display_factory_call_create_single_logon_session_sync (
    DrdDBusLightdmRemoteDisplayFactory *proxy,
    const gchar *arg_client_id,
    guint arg_width,
    guint arg_height,
    GVariant *arg_auth_fd,
    const gchar *arg_address,
    GUnixFDList  *fd_list,
    gchar **out_session_path,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY (drd_dbus_lightdm_remote_display_factory_proxy_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY, DrdDBusLightdmRemoteDisplayFactoryProxy))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY, DrdDBusLightdmRemoteDisplayFactoryProxyClass))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY, DrdDBusLightdmRemoteDisplayFactoryProxyClass))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_PROXY))

typedef struct _DrdDBusLightdmRemoteDisplayFactoryProxy DrdDBusLightdmRemoteDisplayFactoryProxy;
typedef struct _DrdDBusLightdmRemoteDisplayFactoryProxyClass DrdDBusLightdmRemoteDisplayFactoryProxyClass;
typedef struct _DrdDBusLightdmRemoteDisplayFactoryProxyPrivate DrdDBusLightdmRemoteDisplayFactoryProxyPrivate;

struct _DrdDBusLightdmRemoteDisplayFactoryProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  DrdDBusLightdmRemoteDisplayFactoryProxyPrivate *priv;
};

struct _DrdDBusLightdmRemoteDisplayFactoryProxyClass
{
  GDBusProxyClass parent_class;
};

GType drd_dbus_lightdm_remote_display_factory_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactoryProxy, g_object_unref)
#endif

void drd_dbus_lightdm_remote_display_factory_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DrdDBusLightdmRemoteDisplayFactory *drd_dbus_lightdm_remote_display_factory_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
DrdDBusLightdmRemoteDisplayFactory *drd_dbus_lightdm_remote_display_factory_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void drd_dbus_lightdm_remote_display_factory_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DrdDBusLightdmRemoteDisplayFactory *drd_dbus_lightdm_remote_display_factory_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
DrdDBusLightdmRemoteDisplayFactory *drd_dbus_lightdm_remote_display_factory_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON (drd_dbus_lightdm_remote_display_factory_skeleton_get_type ())
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON, DrdDBusLightdmRemoteDisplayFactorySkeleton))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON, DrdDBusLightdmRemoteDisplayFactorySkeletonClass))
#define DRD_DBUS_LIGHTDM_REMOTE_DISPLAY_FACTORY_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON, DrdDBusLightdmRemoteDisplayFactorySkeletonClass))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON))
#define DRD_DBUS_LIGHTDM_IS_REMOTE_DISPLAY_FACTORY_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRD_DBUS_LIGHTDM_TYPE_REMOTE_DISPLAY_FACTORY_SKELETON))

typedef struct _DrdDBusLightdmRemoteDisplayFactorySkeleton DrdDBusLightdmRemoteDisplayFactorySkeleton;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySkeletonClass DrdDBusLightdmRemoteDisplayFactorySkeletonClass;
typedef struct _DrdDBusLightdmRemoteDisplayFactorySkeletonPrivate DrdDBusLightdmRemoteDisplayFactorySkeletonPrivate;

struct _DrdDBusLightdmRemoteDisplayFactorySkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  DrdDBusLightdmRemoteDisplayFactorySkeletonPrivate *priv;
};

struct _DrdDBusLightdmRemoteDisplayFactorySkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType drd_dbus_lightdm_remote_display_factory_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DrdDBusLightdmRemoteDisplayFactorySkeleton, g_object_unref)
#endif

DrdDBusLightdmRemoteDisplayFactory *drd_dbus_lightdm_remote_display_factory_skeleton_new (void);


G_END_DECLS

#endif /* __DRD_DBUS_LIGHTDM_H__ */
